[Cong Le] Implement add competency
hunterbmt/careercoacher pull request #2
Opened 2017-05-12 11:10 UTC by ltc2310

2017-05-12 11:17 UTC, ltc2310 commented
[CF] Add new competency and update activate competency.
Add new competency : It doesn't update page in real time
Update activate competency : It works but don't update page and onChange function when I click in the first time it doesn't work,on second time it works but the value opposite with data in firebase

2017-05-17 08:29 UTC, hunterbmt requested changes

2017-05-17 08:29 UTC, hunterbmt commented on src/Competencies.js
> +var list;
Do not use "var" in ES6

2017-05-17 08:29 UTC, hunterbmt commented on src/Competencies.js
> +     list=this;
Why do we need to assign this to outside variable?

2017-05-17 08:29 UTC, hunterbmt commented on src/Competencies.js
> +class CompetencyPopup extends Component {
one component per file

2017-05-17 08:29 UTC, hunterbmt commented on src/Competencies.js
> +    console.log(list.state.arrayCompetencies);
Removing console.log

2017-05-17 08:29 UTC, hunterbmt commented on src/Competencies.js
> +    var newArrayCompetencies = list.state.arrayCompetencies.push(this.state.competencyName);
Use this instead of outside variable

2017-05-17 13:24 UTC, ltc2310 commented
Fix comment and rewrite function follow new database
How to set auto increment key on competencies when I save new competency?
When I get data source for competencies KMScore to show on table,It return double data competency?

2017-05-18 07:18 UTC, ltc2310 commented
* [CFT] fix add competency follow new database but it has some issues
- I can't set auto increment when I save new competency
- I can't load two table KMS Core and KMS optional in the same time
- When I click on button it always append data on the table

2017-05-18 08:36 UTC, hunterbmt commented on src/Competencies.js
> +    _.map(this.state.competenciesKMSCore, (item, index) => {
const dataSourceCore = _.map(() => return {}) ;
this.setState({dataSourceCode});

2017-05-23 04:06 UTC, closed without merging