[CFT-01] Resolve conflicts page
hunterbmt/careercoacher pull request #3
Opened 2017-05-12 11:26 UTC by JackVuong

Index of questions in compare page is wrong.

2017-05-17 08:28 UTC, hunterbmt requested changes

2017-05-17 08:28 UTC, hunterbmt commented on src/CompareAssessment.js
> +    console.log(this.state.finalAnswers);
Removing console.log

2017-05-17 08:28 UTC, hunterbmt commented on src/CompareAssessment.js
> +              <getData />
why we have getData here ?

2017-05-17 08:28 UTC, hunterbmt commented on src/CompareAssessment.js
> +      switch (question[i].type) {
This logic is way too complicated.
I don't get why we have to re-create "question" for every conflict

2017-05-17 08:28 UTC, hunterbmt commented on src/CompareAssessment.js
> +    getData(`answers/${this.props.name}/${competency}`)
If we use Promise.all, we will end up with way better performance.

2017-05-17 08:28 UTC, hunterbmt commented on src/CompareAssessment.js
> +    console.log(this.state.finalAnswers);
Please remove console.log

2017-05-17 08:28 UTC, hunterbmt commented on src/CompareAssessment.js
> +    Object.values(competencies).map((competency) => this.getQuestion(competency));
Please revisit this logic. It seems unnecessary to me. We can pull all data in one call

2017-05-17 13:04 UTC, JackVuong commented on src/CompareAssessment.js
> +      switch (question[i].type) {
I re-create question for each conflict to easy to display it in solve conflicts page instead of get question again from db.

2017-05-18 08:26 UTC, hunterbmt commented on src/SelfAssessment.js
> +  setAnswers(answer) {
answers

2017-05-22 11:28 UTC, hunterbmt approved these changes

2017-05-22 13:03 UTC, merged