[Cong Le] Complete Add Competency and Add Question for Competency
hunterbmt/careercoacher pull request #8
Opened 2017-05-29 03:49 UTC by ltc2310

2017-05-30 14:46 UTC, hunterbmt requested changes

2017-05-30 14:46 UTC, hunterbmt commented on src/Competencies.js
> +      _.update(this.state.competenciesKMSCore[this.state.keyUpdate], 'activated', () => { return this.state.optionActivated })
Arrow function doesn't need return. We can go with () =? this.state.optionActivated

2017-05-30 14:46 UTC, hunterbmt commented on src/Competencies.js
> +    let columnsKMSCore = [{
Const

2017-05-30 14:46 UTC, hunterbmt commented on src/CompetencyRadar.js
> +    label: 'Must change',
Cannot have the same label

2017-05-30 14:46 UTC, hunterbmt commented on src/GroupManagement.js
> +      members: members,
please use shorthand

2017-05-30 14:46 UTC, hunterbmt commented on src/PersonalInformation.js
> +    let result = false
Please replace with _.some

2017-05-30 14:46 UTC, hunterbmt commented on src/PersonalInformation.js
> +    let manager = _.find(allProjects, (project) => {
please use const

2017-05-31 02:25 UTC, ltc2310 commented on src/CompetencyRadar.js
> +    label: 'Must change',
Hiep Tran is assigned to fix it

2017-05-31 02:26 UTC, ltc2310 commented on src/GroupManagement.js
> +      members: members,
It's in progress

2017-06-06 09:57 UTC, closed without merging